apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  playidentity-mapping
spec:
  hostname: playeconomygateway.eastus.cloudapp.azure.com
  prefix: /identity-svc/
  service: playidentity-service.playidentity
---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  playcatalog-mapping
spec:
  hostname: playeconomygateway.eastus.cloudapp.azure.com
  prefix: /playcatalog-svc/
  service: playcatalog-service.playcatalog
---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  playinventory-mapping
spec:
  hostname: playeconomygateway.eastus.cloudapp.azure.com
  prefix: /playinventory-svc/
  service: playinventory-service.playinventory
---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  playtrading-mapping
spec:
  hostname: playeconomygateway.eastus.cloudapp.azure.com
  prefix: /playtrading-svc/
  service: playtrading-service.playtrading
  allow_upgrade:
    - websocket
---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  frontend-mapping
spec:
  hostname: playeconomygateway.eastus.cloudapp.azure.com
  prefix: /
  service: frontend-client.frontend
---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  seq-mapping
spec:
  hostname: playeconomygateway.eastus.cloudapp.azure.com
  prefix: /seq/
  service: seq.observability

---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  jaeger-mapping
spec:
  hostname: playeconomygateway.eastus.cloudapp.azure.com
  prefix: /jaeger/
  rewrite: ""
  service: jaeger-query.observability:16686